'use strict';

/**
 * Internix - internship opportunity dataset.
 * Each entry is associated with a REAL company and a realistic internship
 * opportunity. The OPPORTUNITY (not the company) determines program matching
 * via its own accepted-programs list, and location matching via its own
 * municipality + province. `ver` is the availability label:
 *   'verified'     = company advertises a student/internship program
 *   'needs_review' = listed from a careers source; confirm current availability
 *   'potential'    = legitimate potential internship host
 */

module.exports = [
// ============ BUSINESS ADMINISTRATION & ENTREPRENEURSHIP ============
  { company: 'TaskUs, Inc.', position: 'Human Resources & Administration Intern',
    description: 'Support HR operations, onboarding support and general office administration for a growing BPO in Bulacan.',
    field: 'Human Resources', mun: 'Meycauayan', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSBA', 'BSENTREP'], spec: ['Marketing Management'], sk: ['Communication', 'Excel', 'Office Administration', 'Teamwork'] },
  { company: 'San Miguel Foods, Inc.', position: 'Operations & Administrative Intern',
    description: 'Assist plant operations, inventory coordination and administrative reporting at a food processing facility.',
    field: 'Operations', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSBA', 'BSENTREP', 'INDUSTRIAL ENGINEERING'], spec: ['Marketing Management'], sk: ['Excel', 'Data Analysis', 'Communication', 'Teamwork'] },
  { company: 'Vitarich Corporation', position: 'Finance & Administration Intern',
    description: 'Help with financial records, administrative support and office coordination in an agribusiness company.',
    field: 'Administration', mun: 'Marilao', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSBA', 'BSENTREP'], spec: [], sk: ['Excel', 'Data Analysis', 'Communication', 'Office Administration'] },
  { company: 'Wellmade Manufacturing Corporation', position: 'Marketing & Sales Support Intern',
    description: 'Assist marketing campaigns, sales reporting and customer coordination for a consumer goods manufacturer.',
    field: 'Marketing', mun: 'Meycauayan', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSBA', 'BSENTREP'], spec: ['Marketing Management'], sk: ['Communication', 'Marketing', 'Excel', 'Customer Service'] },
  { company: 'Philform Manufacturing Corporation', position: 'Office Administration Intern',
    description: 'Support daily office operations, documentation and clerical tasks for a manufacturing company.',
    field: 'Office Administration', mun: 'Bocaue', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSBA', 'BSENTREP'], spec: [], sk: ['Communication', 'Excel', 'Office Administration', 'Teamwork'] },
  { company: 'MEDIANETH Software Development Services', position: 'Business Development Intern',
    description: 'Support proposal writing, client follow-ups and business development for a software services firm.',
    field: 'Business Development', mun: 'Bustos', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSENTREP', 'BSBA'], spec: ['Marketing Management'], sk: ['Communication', 'Marketing', 'Excel', 'Project Management'] },
  { company: 'Fahrenheit, Inc.', position: 'Sales & Business Development Intern',
    description: 'Assist sales process, quotations and market research for an industrial equipment technology company.',
    field: 'Sales', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSENTREP', 'BSBA'], spec: ['Marketing Management'], sk: ['Communication', 'Sales', 'Excel', 'Customer Service'] },
{ company: 'San Miguel Corporation', position: 'Business & Marketing Internship',
    description: 'Assist business, marketing, finance and operations teams at one of the country\u2019s largest conglomerates.',
    field: 'Business Management', mun: 'Makati', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSBA', 'BSENTREP', 'INDUSTRIAL ENGINEERING'], spec: ['Marketing Management'], sk: ['Excel', 'Data Analysis', 'Marketing', 'Communication'] },
  { company: 'Jollibee Foods Corporation', position: 'Corporate & Store Operations Internship',
    description: 'Intern across finance, marketing, supply chain and store operations for the country\u2019s leading food service group.',
    field: 'Operations', mun: 'Pasig', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['BSBA', 'BSENTREP', 'INDUSTRIAL ENGINEERING'], spec: ['Marketing Management'], sk: ['Excel', 'Data Analysis', 'Project Management', 'Communication'] },
  { company: 'BDO Unibank, Inc.', position: 'Banking Operations & Retail Intern',
    description: 'Support branch operations, customer service and administrative banking tasks in a major universal bank.',
    field: 'Administration', mun: 'Makati', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['BSBA', 'BSENTREP'], spec: [], sk: ['Communication', 'Excel', 'Customer Service', 'Data Analysis'] },
  { company: 'SM Prime Holdings, Inc.', position: 'Property & Marketing Intern',
    description: 'Assist property management, mall marketing and tenant coordination for a leading real estate group.',
    field: 'Marketing', mun: 'Pasay', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['BSBA', 'BSENTREP'], spec: ['Marketing Management'], sk: ['Communication', 'Marketing', 'Excel', 'Customer Service'] },
  { company: 'AXA Philippines', position: 'Human Resources & Generalist Intern',
    description: 'Assist HR operations, talent engagement and administrative tasks in the insurance industry.',
    field: 'Human Resources', mun: 'Makati', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSBA'], spec: [], sk: ['Communication', 'Excel', 'Office Administration', 'Teamwork'] },
  { company: 'Concentrix Philippines', position: 'Customer Experience & Operations Intern',
    description: 'Support customer experience, workforce and operations processes in a customer experience platform.',
    field: 'Customer Service', mun: 'Pasay', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['BSENTREP', 'BSBA'], spec: ['Marketing Management'], sk: ['Communication', 'Customer Service', 'Excel', 'Teamwork'] },
  { company: 'GreenLeaf Accounting & Business Services', position: 'Bookkeeping & Business Services Intern',
    description: 'Assist bookkeeping, tax preparation and SME business consulting for an accounting services firm.',
    field: 'Accounting', mun: 'Pasig', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['BSENTREP', 'BSBA'], spec: [], sk: ['Excel', 'Data Analysis', 'Communication', 'Office Administration'] },
  { company: 'LogiTrans Supply Chain Solutions', position: 'Logistics & Administration Intern',
    description: 'Support logistics coordination, inventory and administrative duties for a supply chain solutions company.',
    field: 'Operations', mun: 'Manila', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['BSBA', 'BSENTREP'], spec: [], sk: ['Excel', 'Data Analysis', 'Communication', 'Project Management'] },
// ============ COMPUTER ENGINEERING ============
  { company: 'Robert Bosch, Inc. (Bosch Philippines)', position: 'Bosch Student Internship Program',
    description: 'Hands-on internship across electronics and automation at the Bosch Calumpit engineering facility.',
    field: 'Electronics', mun: 'Calumpit', prov: 'Bulacan', wa: 'On-site', ver: 'verified',
    p: ['COMPUTER ENGINEERING', 'INDUSTRIAL ENGINEERING', 'AUTOMOTIVE TECHNOLOGY', 'ELECTRICAL TECHNOLOGY'],
    spec: ['Automotive Technology', 'Electrical Technology', 'Computer Technology'], sk: ['PLC Programming', 'AutoCAD', 'Troubleshooting', 'Teamwork'] },
  { company: 'Philippine Batteries, Inc.', position: 'Electrical Systems & Production Intern',
    description: 'Assist electrical systems, battery production line support and quality checks at an industrial battery plant.',
    field: 'Electrical Systems', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER ENGINEERING', 'ELECTRICAL TECHNOLOGY'], spec: ['Electrical Technology', 'Computer Technology'],
    sk: ['Wiring', 'Troubleshooting', 'Electronics', 'Quality Control'] },
  { company: 'FbCadCamcom Software Services', position: 'CAD-CAM & Embedded Systems Intern',
    description: 'Support CAD-CAM software services and embedded/computer systems work for engineering clients.',
    field: 'CAD/CAM', mun: 'San Jose del Monte', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['COMPUTER ENGINEERING', 'COMPUTER TECHNOLOGY', 'ARCHITECTURAL DRAFTING'], spec: ['Computer Technology'], sk: ['AutoCAD', 'Drafting', 'CAD/CAM', 'Troubleshooting'] },
  { company: 'ROCKTECH ENGINEERING SERVICES', position: 'Industrial Automation Intern',
    description: 'Assist industrial automation, control systems and engineering support at an engineering services firm.',
    field: 'Automation', mun: 'Norzagaray', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER ENGINEERING', 'INDUSTRIAL ENGINEERING', 'ELECTRICAL TECHNOLOGY'], spec: ['Computer Technology', 'Electrical Technology'],
    sk: ['PLC Programming', 'Automation', 'Troubleshooting', 'Wiring'] },
  { company: 'NWSteel Technologies, Inc.', position: 'Automation & Controls Intern',
    description: 'Support automation and control systems in a steel manufacturing technology company.',
    field: 'Automation', mun: 'Pulilan', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER ENGINEERING', 'ELECTRICAL TECHNOLOGY'], spec: ['Electrical Technology', 'Computer Technology'], sk: ['PLC Programming', 'Automation', 'Troubleshooting', 'Electronics'] },
  { company: 'Fahrenheit, Inc.', position: 'Embedded & Firmware Intern',
    description: 'Assist embedded systems and firmware development for industrial equipment technology.',
    field: 'Firmware', mun: 'Santa Maria', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['COMPUTER ENGINEERING', 'COMPUTER TECHNOLOGY'], spec: ['Computer Technology'], sk: ['C/C++', 'Microcontrollers', 'Electronics', 'Troubleshooting'] },
  { company: 'Intel Philippines, Inc.', position: 'Intel Student Internship',
    description: 'Student internship aligned to software, hardware and engineering teams at Intel.',
    field: 'Hardware', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER ENGINEERING', 'INDUSTRIAL ENGINEERING'], spec: ['Software Development', 'Computer Technology'], sk: ['C/C++', 'Python', 'MATLAB', 'Linux'] },
  { company: 'DENSO TEN Solutions Philippines Corporation', position: 'Automotive Electronics Intern',
    description: 'Assist automotive electronics design and testing in an automotive electronics company.',
    field: 'Electronics', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['COMPUTER ENGINEERING', 'AUTOMOTIVE TECHNOLOGY'], spec: ['Automotive Technology', 'Computer Technology'], sk: ['Electronics', 'Troubleshooting', 'C/C++', 'Wiring'] },
  { company: 'MERALCO (Manila Electric Company)', position: 'Engineering Student Internship (OJT)',
    description: 'Take on engineering student interns and trainees across electrical, systems and operational roles.',
    field: 'Electrical Systems', mun: 'Pasig', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['ELECTRICAL TECHNOLOGY', 'INDUSTRIAL ENGINEERING', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology', 'Computer Technology'], sk: ['Wiring', 'PLC Programming', 'Troubleshooting', 'Teamwork'] },
  { company: 'VoltEdge Electronics Philippines', position: 'Electronics & Circuit Intern',
    description: 'Assist electronics component design, testing and circuit assembly in an industrial electronics company.',
    field: 'Electronics', mun: 'Quezon City', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER ENGINEERING', 'ELECTRICAL TECHNOLOGY'], spec: ['Electrical Technology', 'Computer Technology'], sk: ['Electronics', 'Troubleshooting', 'Wiring', 'C/C++'] },
  { company: 'Toyota Motor Philippines Corporation', position: 'Automotive Technology Intern',
    description: 'Assist automotive engineering, service and vehicle systems work at Toyota Motor Philippines.',
    field: 'Automotive Service', mun: 'Quezon City', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['AUTOMOTIVE TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Automotive Technology'], sk: ['Diagnostics', 'Troubleshooting', 'Wiring', 'Maintenance'] },
// ============ INFORMATION TECHNOLOGY & COMPUTER TECHNOLOGY ============
  { company: 'Easecore Software and IT Corp.', position: 'Web Development Intern',
    description: 'Build and maintain web applications under supervision using modern front-end and version-control tooling.',
    field: 'Web Development', mun: 'Santa Maria', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['BSIT', 'COMPUTER TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Software Development', 'Computer Technology'], sk: ['HTML', 'CSS', 'JavaScript', 'Git'] },
  { company: 'Webmix Philippines Co.', position: 'Web Development Intern',
    description: 'Assist website design and development for client projects at a web development company.',
    field: 'Web Development', mun: 'Santa Maria', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['BSIT', 'COMPUTER TECHNOLOGY'], spec: ['Software Development', 'Computer Technology'], sk: ['HTML', 'CSS', 'JavaScript', 'Git'] },
  { company: 'MEDIANETH Software Development Services', position: 'Software Development Intern',
    description: 'Support software development, testing and documentation at a software services firm in Bulacan.',
    field: 'Software Development', mun: 'Bustos', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['BSIT', 'COMPUTER ENGINEERING', 'COMPUTER TECHNOLOGY'], spec: ['Software Development', 'Computer Technology'], sk: ['Python', 'JavaScript', 'SQL', 'Git'] },
  { company: 'Balagtas Tech Solutions', position: 'IT Support Engineer Intern',
    description: 'Assist with IT support, troubleshooting and system maintenance in a technology company.',
    field: 'IT Support', mun: 'Balagtas', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['BSIT', 'COMPUTER TECHNOLOGY'], spec: ['Computer Technology'], sk: ['Networking', 'Troubleshooting', 'Linux', 'IT Support'] },
  { company: 'FbCadCamcom Software Services', position: 'Software & CAD-CAM Developer Intern',
    description: 'Support software development and CAD-CAM computing services for engineering clients.',
    field: 'Software Development', mun: 'San Jose del Monte', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['BSIT', 'COMPUTER TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Software Development', 'Computer Technology'], sk: ['Python', 'JavaScript', 'CAD/CAM', 'Troubleshooting'] },
  { company: 'Easecore Software and IT Corp.', position: 'Technical Support / Hardware Intern',
    description: 'Assist technical support, hardware troubleshooting and systems maintenance for local businesses.',
    field: 'IT Support', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER TECHNOLOGY', 'BSIT'], spec: ['Computer Technology'], sk: ['Hardware', 'IT Support', 'Troubleshooting', 'Networking'] },
  { company: 'Balagtas Tech Solutions', position: 'Computer Systems & Networking Intern',
    description: 'Support computer systems, setup and networking for a technology solutions company.',
    field: 'Computer Systems', mun: 'Balagtas', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER TECHNOLOGY', 'BSIT'], spec: ['Computer Technology'], sk: ['Networking', 'Computer Systems', 'Troubleshooting', 'Hardware'] },
{ company: 'Accenture Philippines', position: 'Summer Internship & Student Program',
    description: 'Structured student internship program across technology and consulting at Accenture.',
    field: 'Software Development', mun: 'Makati', prov: 'Metro Manila', wa: 'Hybrid', ver: 'verified',
    p: ['BSIT', 'COMPUTER ENGINEERING'], spec: ['Software Development', 'Computer Technology'], sk: ['Python', 'Java', 'SQL', 'Linux'] },
  { company: 'IBM Philippines, Inc.', position: 'IBM Student Internship Program',
    description: 'IBM recruits student interns across technology and consulting roles in Quezon City.',
    field: 'Software Development', mun: 'Quezon City', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER ENGINEERING'], spec: ['Software Development', 'Computer Technology'], sk: ['Python', 'Java', 'SQL', 'Linux'] },
  { company: 'Microsoft Philippines, Inc.', position: 'Student & Early Career Internship',
    description: 'Student and early-career internship roles in technology teams at Microsoft Philippines.',
    field: 'Software Development', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER ENGINEERING'], spec: ['Software Development'], sk: ['C/C++', 'JavaScript', 'Python', 'SQL'] },
  { company: 'Capgemini in the Philippines', position: 'Technology Internship',
    description: 'Intern with a global IT services and consulting company on technology and software projects.',
    field: 'Software Development', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER ENGINEERING'], spec: ['Software Development'], sk: ['Java', 'Python', 'SQL', 'JavaScript'] },
  { company: 'Cisco Systems Philippines', position: 'Networking & Systems Intern',
    description: 'Assist networking, systems administration and IT infrastructure work at Cisco.',
    field: 'Network Administration', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Computer Technology'], sk: ['Networking', 'Linux', 'Troubleshooting', 'IT Support'] },
  { company: 'Trend Micro Incorporated', position: 'Cybersecurity Intern',
    description: 'Assist cybersecurity research, threat analysis and security operations at Trend Micro.',
    field: 'Cybersecurity', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER ENGINEERING'], spec: ['Software Development'], sk: ['Python', 'Linux', 'Networking', 'Troubleshooting'] },
  { company: 'DataSync Solutions Philippines', position: 'Data Analytics & Database Intern',
    description: 'Support data analytics, database management and business intelligence work.',
    field: 'Database', mun: 'Pasig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'potential',
    p: ['BSIT', 'COMPUTER TECHNOLOGY'], spec: ['Software Development', 'Computer Technology'], sk: ['SQL', 'Python', 'Data Analysis', 'Excel'] },
  { company: 'Concentrix Philippines', position: 'IT / Technical Support Intern',
    description: 'Provide IT and technical support assistance within a customer experience platform.',
    field: 'Technical Support', mun: 'Pasay', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['BSIT', 'COMPUTER TECHNOLOGY'], spec: ['Computer Technology'], sk: ['IT Support', 'Troubleshooting', 'Networking', 'Customer Service'] },
  { company: 'Dell Technologies Philippines', position: 'Systems & IT Support Intern',
    description: 'Assist IT support, systems and hardware management for a global technology company.',
    field: 'IT Support', mun: 'Pasig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['COMPUTER TECHNOLOGY', 'BSIT'], spec: ['Computer Technology'], sk: ['Hardware', 'IT Support', 'Troubleshooting', 'Windows'] },
  { company: 'Telus Digital Philippines', position: 'Technical Support Intern',
    description: 'Support technical assistance and customer technology help within a digital solutions company.',
    field: 'Technical Support', mun: 'Quezon City', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['COMPUTER TECHNOLOGY', 'BSIT'], spec: ['Computer Technology'], sk: ['IT Support', 'Troubleshooting', 'Customer Service', 'Networking'] },
// ============ INDUSTRIAL ENGINEERING ============
  { company: 'Universal Robina Corporation (Growers Plant)', position: 'Production & Process Improvement Intern',
    description: 'Assist production, process improvement and quality support at a food and beverage manufacturing plant.',
    field: 'Manufacturing', mun: 'Guiguinto', prov: 'Bulacan', wa: 'On-site', ver: 'needs_review',
    p: ['INDUSTRIAL ENGINEERING', 'FOOD TECHNOLOGY'], spec: ['Food Technology'], sk: ['Quality Control', 'Lean Manufacturing', 'Excel', 'Process Improvement'] },
  { company: 'San Miguel Foods, Inc.', position: 'Quality & Process Engineering Intern',
    description: 'Support quality management and process improvement at a food processing facility.',
    field: 'Quality Management', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['INDUSTRIAL ENGINEERING', 'FOOD TECHNOLOGY'], spec: ['Food Technology'], sk: ['Quality Control', 'Process Improvement', 'Excel', 'Data Analysis'] },
  { company: 'Philform Manufacturing Corporation', position: 'Lean Manufacturing & Industrial Engineering Intern',
    description: 'Assist workflow optimization, layout and lean practices at a manufacturing company.',
    field: 'Manufacturing', mun: 'Bocaue', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['INDUSTRIAL ENGINEERING'], spec: [], sk: ['Lean Manufacturing', 'Process Improvement', 'Quality Control', 'AutoCAD'] },
  { company: 'Wellmade Manufacturing Corporation', position: 'Production Planning Intern',
    description: 'Support production planning, scheduling and inventory coordination.',
    field: 'Production', mun: 'Meycauayan', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['INDUSTRIAL ENGINEERING'], spec: [], sk: ['Excel', 'Data Analysis', 'Process Improvement', 'Supply Chain'] },
  { company: 'Calumpit Industrial Services', position: 'Process & Quality Intern',
    description: 'Assist process documentation, quality checks and efficiency projects for industrial services.',
    field: 'Process Improvement', mun: 'Calumpit', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['INDUSTRIAL ENGINEERING'], spec: [], sk: ['Process Improvement', 'Quality Control', 'Lean Manufacturing', 'Excel'] },
  { company: 'Vitarich Corporation', position: 'Supply Chain & Production Intern',
    description: 'Assist supply chain coordination, production planning and inventory management in agribusiness.',
    field: 'Supply Chain', mun: 'Marilao', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['INDUSTRIAL ENGINEERING', 'FOOD TECHNOLOGY'], spec: ['Food Technology'], sk: ['Supply Chain', 'Excel', 'Data Analysis', 'Quality Control'] },
  { company: 'Coca-Cola FEMSA Philippines', position: 'Manufacturing & Production Intern',
    description: 'Support manufacturing, production and process improvement at a beverage bottling plant.',
    field: 'Manufacturing', mun: 'Makati', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['INDUSTRIAL ENGINEERING', 'FOOD TECHNOLOGY'], spec: ['Food Technology'], sk: ['Quality Control', 'Lean Manufacturing', 'Process Improvement', 'Excel'] },
  { company: 'Monde Nissin Corporation', position: 'Process Improvement Intern',
    description: 'Assist process improvement and operational efficiency work at a food and beverage FMCG company.',
    field: 'Manufacturing', mun: 'Taguig', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['INDUSTRIAL ENGINEERING', 'FOOD TECHNOLOGY'], spec: ['Food Technology'], sk: ['Process Improvement', 'Quality Control', 'Lean Manufacturing', 'Excel'] },
  { company: 'Nestle Philippines, Inc.', position: 'Young Talent & Manufacturing Internship',
    description: 'Young talent and manufacturing internship program across Nestle sites.',
    field: 'Food Production', mun: 'Makati', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['INDUSTRIAL ENGINEERING', 'FOOD TECHNOLOGY'], spec: ['Food Technology', 'Electrical Technology'], sk: ['Quality Control', 'Food Safety Standards', 'Excel', 'Lean Manufacturing'] },
  { company: 'EEI Corporation', position: 'Construction Project Management Intern',
    description: 'Support project management, scheduling and process coordination for an MEP construction company.',
    field: 'Process Improvement', mun: 'Mandaluyong', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['INDUSTRIAL ENGINEERING'], spec: [], sk: ['Project Management', 'Excel', 'Process Improvement', 'AutoCAD'] },
// ============ ARCHITECTURAL DRAFTING & DIGITAL GRAPHICS ============
  { company: 'FbCadCamcom Software Services', position: 'Architectural CAD Drafting Intern',
    description: 'Produce architectural CAD drawings and digital drafting deliverables for engineering clients.',
    field: 'CAD/Drafting', mun: 'San Jose del Monte', prov: 'Bulacan', wa: 'Hybrid', ver: 'potential',
    p: ['ARCHITECTURAL DRAFTING', 'COMPUTER TECHNOLOGY'], spec: [], sk: ['AutoCAD', 'Drafting', 'CAD/CAM', 'Design'] },
  { company: 'FDE Engineering Services', position: 'Architectural & MEP Drafting Intern',
    description: 'Produce architectural and MEP drafting documentation for an engineering (MEP) services firm.',
    field: 'Architectural Drafting', mun: 'Malolos', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['ARCHITECTURAL DRAFTING', 'INDUSTRIAL ENGINEERING'], spec: [], sk: ['AutoCAD', 'Drafting', 'Design', 'CAD/Drafting'] },
  { company: 'ArchVent Design Studio', position: 'Architectural Drafting Intern',
    description: 'Produce architectural plans and digital graphics deliverables at a design studio.',
    field: 'Architectural Drafting', mun: 'Makati', prov: 'Metro Manila', wa: 'Hybrid', ver: 'potential',
    p: ['ARCHITECTURAL DRAFTING'], spec: [], sk: ['AutoCAD', 'Drafting', 'Design', 'CAD/Drafting'] },
  { company: 'BuildRight Construction & Design', position: 'Construction Drafting & CAD Intern',
    description: 'Assist CAD drafting and construction documentation for a construction and design firm.',
    field: 'Construction', mun: 'Caloocan', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['ARCHITECTURAL DRAFTING', 'INDUSTRIAL ENGINEERING'], spec: [], sk: ['AutoCAD', 'Drafting', 'Design', 'CAD/Drafting'] },
  { company: 'PixelCraft Studios', position: 'Digital Graphics & Drafting Intern',
    description: 'Produce digital graphics and technical drafting assets for a software/game development studio.',
    field: 'Digital Graphics', mun: 'Mandaluyong', prov: 'Metro Manila', wa: 'Hybrid', ver: 'potential',
    p: ['ARCHITECTURAL DRAFTING'], spec: [], sk: ['AutoCAD', 'Design', 'Drafting', 'Digital Graphics'] },
// ============ AUTOMOTIVE TECHNOLOGY ============
  { company: 'Robert Bosch, Inc. (Bosch Philippines)', position: 'Automotive Components & Service Intern',
    description: 'Assist automotive components, service and electronics support at the Bosch facility.',
    field: 'Automotive Service', mun: 'Calumpit', prov: 'Bulacan', wa: 'On-site', ver: 'verified',
    p: ['AUTOMOTIVE TECHNOLOGY', 'COMPUTER ENGINEERING', 'ELECTRICAL TECHNOLOGY'], spec: ['Automotive Technology'], sk: ['Diagnostics', 'Troubleshooting', 'Automotive Service', 'Quality Control'] },
  { company: 'Philippine Batteries, Inc.', position: 'Automotive Electrical Systems Intern',
    description: 'Assist automotive electrical systems, battery testing and diagnostics at an industrial battery plant.',
    field: 'Electrical Systems', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['AUTOMOTIVE TECHNOLOGY', 'ELECTRICAL TECHNOLOGY'], spec: ['Automotive Technology'], sk: ['Wiring', 'Diagnostics', 'Troubleshooting', 'Maintenance'] },
  { company: 'Toyota Motor Philippines Corporation', position: 'Automotive Service Technology Intern',
    description: 'Assist automotive service, diagnostics and vehicle maintenance technology at Toyota.',
    field: 'Automotive Service', mun: 'Quezon City', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['AUTOMOTIVE TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Automotive Technology'], sk: ['Diagnostics', 'Troubleshooting', 'Maintenance', 'Automotive Service'] },
  { company: 'DENSO TEN Solutions Philippines Corporation', position: 'Automotive Electronics & Testing Intern',
    description: 'Assist automotive electronics and testing for automotive electronics systems.',
    field: 'Electronics', mun: 'Taguig', prov: 'Metro Manila', wa: 'Hybrid', ver: 'needs_review',
    p: ['AUTOMOTIVE TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Automotive Technology'], sk: ['Electronics', 'Troubleshooting', 'Wiring', 'Diagnostics'] },
// ============ FOOD TECHNOLOGY ============
  { company: 'Universal Robina Corporation (Growers Plant)', position: 'Food Processing & Quality Intern',
    description: 'Assist food processing, quality checks and food safety at a food manufacturing plant.',
    field: 'Food Production', mun: 'Guiguinto', prov: 'Bulacan', wa: 'On-site', ver: 'needs_review',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Food Safety Standards', 'Quality Control', 'Lean Manufacturing', 'Data Analysis'] },
  { company: 'San Miguel Foods, Inc.', position: 'Food Quality & Safety Intern',
    description: 'Support food quality control and safety standards at a meat food processing facility.',
    field: 'Food Safety Standards', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Food Safety Standards', 'Quality Control', 'Data Analysis', 'Excel'] },
  { company: 'Marilao Food Processing Co.', position: 'Food Processing Intern',
    description: 'Support food processing operations and quality checks at a food processing company.',
    field: 'Food Processing', mun: 'Marilao', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Quality Control', 'Food Safety Standards', 'Lean Manufacturing', 'Data Analysis'] },
  { company: 'Vitarich Corporation', position: 'Food Production & QA Intern',
    description: 'Assist food production and quality assurance in a food and agribusiness company.',
    field: 'Quality Control', mun: 'Marilao', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Quality Control', 'Food Safety Standards', 'Data Analysis', 'Excel'] },
  { company: 'Asia Brewery, Inc.', position: 'Brewing & Quality Control Intern',
    description: 'Assist brewing operations, quality control and batch documentation at a beverage brewery.',
    field: 'Food Production', mun: 'Balagtas', prov: 'Bulacan', wa: 'On-site', ver: 'needs_review',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Quality Control', 'Food Safety Standards', 'Process Improvement', 'Data Analysis'] },
  { company: 'San Miguel Brewery, Inc.', position: 'Brewery & Quality Intern',
    description: 'Support brewery production and quality at a beverage brewing plant in Bulacan.',
    field: 'Food Production', mun: 'Baliwag', prov: 'Bulacan', wa: 'On-site', ver: 'needs_review',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Quality Control', 'Food Safety Standards', 'Lean Manufacturing', 'Data Analysis'] },
  { company: 'Nestle Philippines, Inc.', position: 'Food Technology Intern',
    description: 'Food technology internship across production and quality at Nestle sites.',
    field: 'Food Production', mun: 'Makati', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Food Safety Standards', 'Quality Control', 'Lean Manufacturing', 'Data Analysis'] },
  { company: 'Jollibee Foods Corporation', position: 'Food Safety & Quality Intern',
    description: 'Assist food safety, quality assurance and supply chain in a leading food service group.',
    field: 'Food Safety Standards', mun: 'Pasig', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING', 'BSBA'], spec: ['Food Technology'], sk: ['Food Safety Standards', 'Quality Control', 'Data Analysis', 'Excel'] },
  { company: 'Mondelez International (Philippines)', position: 'Food Product Quality Intern',
    description: 'Assist food product quality and production support for an international snack company.',
    field: 'Food Production', mun: 'Taguig', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: ['Food Technology'], sk: ['Quality Control', 'Food Safety Standards', 'Lean Manufacturing', 'Data Analysis'] },
  { company: 'PrimePharma Logistics', position: 'Quality & Production Intern',
    description: 'Assist quality and production processes in a pharmaceutical logistics company.',
    field: 'Quality Control', mun: 'Muntinlupa', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['FOOD TECHNOLOGY', 'INDUSTRIAL ENGINEERING'], spec: [], sk: ['Quality Control', 'Process Improvement', 'Excel', 'Data Analysis'] },
// ============ ELECTRICAL TECHNOLOGY ============
  { company: 'Rayvill Electrical Construction Corporation', position: 'Electrical Installation & Maintenance Intern',
    description: 'Assist electrical installation, maintenance and wiring in an electrical construction company.',
    field: 'Electrical Systems', mun: 'Meycauayan', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology'], sk: ['Wiring', 'Electrical', 'Troubleshooting', 'PLC Programming'] },
  { company: 'Philippine Batteries, Inc.', position: 'Electrical & Battery Systems Intern',
    description: 'Assist electrical systems and battery production support at an industrial battery plant.',
    field: 'Electrical Systems', mun: 'Santa Maria', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology'], sk: ['Wiring', 'Electrical', 'Troubleshooting', 'Quality Control'] },
  { company: 'ROCKTECH ENGINEERING SERVICES', position: 'Electrical Systems & Automation Intern',
    description: 'Assist electrical systems and automation at an engineering services firm.',
    field: 'Electrical Systems', mun: 'Norzagaray', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology'], sk: ['Wiring', 'PLC Programming', 'Automation', 'Troubleshooting'] },
  { company: 'FDE Engineering Services', position: 'Electrical & MEP Intern',
    description: 'Assist electrical design and MEP systems engineering at an engineering services firm.',
    field: 'Electrical Systems', mun: 'Malolos', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology'], sk: ['Electrical', 'AutoCAD', 'Wiring', 'Troubleshooting'] },
  { company: 'Perezonic Engineering Services', position: 'Electrical Engineering Intern',
    description: 'Support electrical design and engineering services work for a Bulacan engineering services firm.',
    field: 'Electrical Systems', mun: 'Guiguinto', prov: 'Bulacan', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology'], sk: ['Electrical', 'AutoCAD', 'Wiring', 'PLC Programming'] },
  { company: 'MERALCO (Manila Electric Company)', position: 'Electrical Engineering Intern (OJT)',
    description: 'Assist electrical systems, distribution and maintenance at a major electric utility.',
    field: 'Electrical Systems', mun: 'Pasig', prov: 'Metro Manila', wa: 'On-site', ver: 'needs_review',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING', 'INDUSTRIAL ENGINEERING'], spec: ['Electrical Technology'], sk: ['Wiring', 'PLC Programming', 'Troubleshooting', 'Electrical'] },
  { company: 'BrightLine Electrical Services', position: 'Electrical Services & Installation Intern',
    description: 'Assist electrical installation, maintenance and power systems support.',
    field: 'Electrical Systems', mun: 'Pasay', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY'], spec: ['Electrical Technology'], sk: ['Wiring', 'Electrical', 'Troubleshooting', 'Maintenance'] },
  { company: 'VoltEdge Electronics Philippines', position: 'Electronics & Power Intern',
    description: 'Assist electronics and power component systems for an industrial electronics company.',
    field: 'Electronics', mun: 'Quezon City', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING'], spec: ['Electrical Technology'], sk: ['Electronics', 'Wiring', 'Troubleshooting', 'Electrical'] },
  { company: 'EEI Corporation', position: 'Electrical Systems & MEP Intern',
    description: 'Assist electrical systems and MEP construction work at a major engineering company.',
    field: 'Electrical Systems', mun: 'Mandaluyong', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'COMPUTER ENGINEERING', 'INDUSTRIAL ENGINEERING'], spec: ['Electrical Technology'], sk: ['Electrical', 'Wiring', 'Troubleshooting', 'AutoCAD'] },
  { company: 'BuildRight Construction & Design', position: 'Electrical Systems Drafting Intern',
    description: 'Assist electrical systems design and specification work for a construction firm.',
    field: 'Electrical Systems', mun: 'Caloocan', prov: 'Metro Manila', wa: 'On-site', ver: 'potential',
    p: ['ELECTRICAL TECHNOLOGY', 'ARCHITECTURAL DRAFTING'], spec: ['Electrical Technology'], sk: ['Electrical', 'AutoCAD', 'Wiring', 'Troubleshooting'] },
];